---
- name: Add geoipupdate  repository
  ansible.builtin.apt_repository:
    repo: ppa:maxmind/ppa

- name: Install geoipupdate
  apt:
    name: geoipupdate
    update_cache: yes
    # state: present


- name: Update geoipupdate config files
  become: true
  template:
    src: templates/conf
    dest: "/etc/GeoIP.conf"
- name: Update geoipupdate config files
  ansible.builtin.cron:
    name: "Update geoipupdate config files"
    user: root
    minute: '30'
    hour: '3'
    weekday: '2'
    job: "/usr/local/bin/geoipupdate"
