---
- name: Install fail2ban
  apt:
    name: fail2ban
    state: latest


- name: run service fail2ban
  become: true
  command: systemctl start fail2ban

- name: enable service fail2ban
  become: true
  command: systemctl enable fail2ban
