---
- name: Add the PostgreSQL repository key to the apt trusted keys
  apt_key: 
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present


# - name: Add the PostgreSQL repository to the apt sources list
#   command: sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
#   become: no

- name: Add the PostgreSQL repository to the apt sources list
  apt_repository: 
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ distribution_name }}-pgdg main
    filename: pgdg.list
    state: present



- name: Install PostgreSQL
  become: yes
  apt:
    name: 
    - postgresql-12
    - postgresql-client-12
    - libpq-dev
    - python3-pip
    update_cache: yes
    state: present

- name: install psycopg2
  pip:
    name:
      - psycopg2-binary


- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes


- name: restart postgresql server
  service: name=postgresql state=restarted enabled=yes


- name: Create Postgres user 
  postgresql_user:
    name: "{{ postgres_user }}"
    password: "{{ postgres_pass }}"
    state: present
  become: True
  become_user: postgres
